# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"moo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://deven-gqc.github.io/foo/"

git_url = "https://github.com/deven-gqc/foo/tree/{branch}/"

def custom_doc_links(name): return None
