# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['moo', 'boo']

# Cell
def moo(x: int, # input
       )->int: # output
  "returns the number itself"
  return x

# Cell
def boo(x: int, # input
       )->int: # output
  "returns the number itself"
  return x